# Generated by Django 5.2.8 on 2025-11-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
